"""empty message

Revision ID: 620918c7c2fc
Revises: 205f1257687f
Create Date: 2019-03-06 13:15:58.958473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '620918c7c2fc'
down_revision = '205f1257687f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('location', 'stations', ['latitude', 'longitude'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('location', 'stations', type_='unique')
    # ### end Alembic commands ###
