"""empty message

Revision ID: bdef02419317
Revises: 39f944beaf11
Create Date: 2019-03-21 16:15:00.901975

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bdef02419317'
down_revision = '39f944beaf11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('expires_at', sa.DateTime(), nullable=False))
    op.drop_column('sessions', 'created_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('sessions', 'expires_at')
    # ### end Alembic commands ###
