"""empty message

Revision ID: 39f944beaf11
Revises: c68737eaea75
Create Date: 2019-03-21 16:14:06.292224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39f944beaf11'
down_revision = 'c68737eaea75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.drop_column('sessions', 'expires_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('expires_at', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('sessions', 'created_at')
    # ### end Alembic commands ###
